### ISSUE TITLE
Deselect Snippets functionality 

### ISSUE THREAD

**Issue by Sophyia7** [pieces-app/example-ts#49]
**Problem Statement:**
Currently, there is no functionality to deselect snippets after selecting a specific one. This limitation poses an issue for users who may need to modify their selection or choose a different snippet without starting the process over.

**Proposed Solution Steps:**
1. Implement a clear and visible "Deselect" option within the snippet selection interface.
2. Allow users to click on the selected snippet again to deselect it.
3. Provide a keyboard shortcut for quick snippet deselection.
4. Ensure that the deselection process is intuitive and user-friendly to enhance the overall user experience.

This fix should improve the flexibility and user control within the snippet selection, improving the overall usability of the project.

**Comment by jordan-pieces** [comment]
@jatin-nandwani would love to have you get started here 👍 let us know if you have any further questions or need anything on this task

**Comment by jatin-nandwani** [comment]
@jordan-pieces 
Just wanted to understand which view are we talking about
Like to selection can you please help me understand how can I reach the Point where Snippet selection is made?
Apologies for the late response, was busy with some work.

**Comment by jordan-pieces** [comment]
no problem @jatin-nandwani - some goals here would be as follows, and they all relate to the grid view that is at the top of the page: 

- [ ] make the second click on a selected snippet 'deselect the snippet' and remove the hover color from that snippet
- [ ] add a `<button>` that allows you to clear your selection 

if possible: 
- [ ] add in a shortcut, where a user can press a key and remove selection if there if any selection present

Hopefully this sheds clarifies the information and gives you some specific tasks as well 👍 Feel free to reach out for any other questions

**Comment by jatin-nandwani** [comment]
Hey @jordan-pieces 
Thanks for getting back on this. Please find further questions mentioned herein. Since this is my first time contributing Open Source, just wanted to align if I'm getting it correctly

1. Upon running the application and connecting with Pieces OS and saving snippets, this is what the app now looks like:
<img width="1233" alt="Screenshot 2024-01-06 at 5 53 58 PM" src="https://github.com/pieces-app/example-ts/assets/29120497/728249f9-d884-46d2-94fd-2bed37004db5">

2. Now from the above when I select a snippet, this is what it looks like:
<img width="1235" alt="Screenshot 2024-01-06 at 5 57 06 PM" src="https://github.com/pieces-app/example-ts/assets/29120497/974adad9-b1d4-47d0-9d87-c376f3e409ba">

3. Upon re-clicking the same snippet its deselecting the snippet, so that's sorted but I believe from the above image, just besides the Delete button you need another button to deselect the snippet and remove the Blue color background. 

Is my understanding correct, Shall i go ahead and implement the functionality?

**Comment by jordan-pieces** [comment]
Yes that is correct @jatin-nandwani - and would be a great implementation here. The other part of this would be to add the same logic that you mention in (3.) above to a particular keyboard shortcut, and to try implementing that. an example of something like that is this: https://www.fullstacklabs.co/blog/keyboard-shortcuts-with-react-hooks

Now i understand this is much more in depth and around the react side of the application but if you are interested in exploring it more than i would love/be happy to assist. 👍

**Comment by jordan-pieces** [comment]
hey @jatin-nandwani just wanted to check in and see how this is going and if there is anything i can do to assist?

**Comment by jatin-nandwani** [comment]
Hi @jordan-pieces 
Apologies, I'm not getting the time to work on this. 
It seems you got a PR request, so please go ahead and review the same. Thanks
